// Standalone OIDC issuer for Cloudflare-worker → Azure federation.
//
// Publishes the discovery document + JWKS that Azure Entra fetches to validate
// the self-signed client assertions sessions-telemetry-gateway mints (see
// ./oidc-sign.ts and ./telemetry-gateway.ts). This is the whole point of the
// "zero Azure secret" design: no connection string or instrumentation key ever
// leaves this repo — Azure trusts this issuer's public key instead.
//
// This worker holds ONLY public keys. Signing happens in the telemetry
// gateway, which reads the matching private key from the OIDC_SIGNING_KEY
// Secrets Store entry. The gateway's OIDC_SIGNING_KID (in
// hub/wrangler.telemetry-gateway.jsonc) must always match ACTIVE_KID below —
// that's the kid it stamps in its JWT header and the one Entra actually needs
// to resolve against a key in PUBLIC_JWKS to verify the signature.
//
// Ported from youtube-mirror's worker/oidc-issuer.ts (GCP federation removed —
// this deployment only federates to Azure), then extended to publish a JWKS
// **array** rather than a single key, so a signing-key rotation can carry both
// the old and new key simultaneously while Entra's (and any other relying
// party's) cached copy of this endpoint catches up.
//
// Rotation sequence (see also infra/cf/telemetry.md "Rotate the signing key"):
//   1. Generate a new keypair (`node scripts/generate-gateway-key.mjs`).
//   2. Add its public JWK to PUBLIC_JWKS (keep the old one too) and redeploy
//      this worker. Do NOT change ACTIVE_KID yet.
//   3. Wait at least one Cache-Control max-age window (below) so every cached
//      copy of /.well-known/jwks.json — Entra's included — has the new key.
//   4. Bind the new private key as OIDC_SIGNING_KEY, set OIDC_SIGNING_KID to
//      the new kid, and set ACTIVE_KID here to match; redeploy both workers.
//   5. Once nothing is minting assertions with the old kid (immediately, since
//      step 4 was one deploy), remove the old entry from PUBLIC_JWKS and
//      redeploy this worker again.

interface Env {
  ISSUER_URL: string;
}

interface Jwk {
  kty: string;
  kid: string;
  n: string;
  e: string;
  alg: string;
  use: string;
}

// The kid the telemetry gateway currently signs with (must equal
// OIDC_SIGNING_KID on sessions-telemetry-gateway). During a rotation this is
// the OLD kid until step 4 above flips it to the new one.
const ACTIVE_KID = "5c98ea52";

// PLACEHOLDER — generated by `node scripts/generate-gateway-key.mjs` for local
// dev/typecheck only; NOT paired with any private key ever bound as
// OIDC_SIGNING_KEY. Swap this for the real public JWK(s) at M4 deploy time
// (see infra/cf/telemetry.md), keeping ACTIVE_KID in sync.
const PUBLIC_JWKS: Jwk[] = [
  {
    kty: "RSA",
    kid: "5c98ea52",
    n: "6G02tlLeCFnQbfBr_WjGYcd1q4MwXtrtu6Io2np4sszP2UOP3c9w46flw80EqWhKYO1YoaOPJGPtWuiYSOyLTXOfJ4q0wSF3zK2DR4aLyoJb_A1_khIdM2CCVs_Ec5eJOAAaSXRLr8SkV3D8ro_ejdsGrNKhooc3KJfy8K_joY2n9efTsN3LwSsibP_E3kyNWDzUyLykKdx6xOOW5M0T2Kj-IpzRc6sl4GcapvkEIBENOAcr5WbwqQ3VcG6zyy0sbaYiUCkhMbgOoQPnGhNpiF0mZAjehkkO00D7VIy6NNFFDKWaXO2cohH5kCUrgW7W4zbH8B6Y7bZr_b3Fkr5eeQ",
    e: "AQAB",
    alg: "RS256",
    use: "sig",
  },
];

// Rotation-tolerant: short enough that a newly-published key propagates to
// relying parties (Entra's JWKS cache included) well within the window a
// rotation actually waits (step 3 above), unlike the previous 1h value.
const JWKS_CACHE_CONTROL = "public, max-age=300";

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const path = new URL(request.url).pathname;

    if (request.method === "GET" && path === "/.well-known/openid-configuration") {
      return Response.json(
        {
          issuer: env.ISSUER_URL,
          jwks_uri: `${env.ISSUER_URL}/.well-known/jwks.json`,
          response_types_supported: ["id_token"],
          subject_types_supported: ["public"],
          id_token_signing_alg_values_supported: ["RS256"],
        },
        { headers: { "Cache-Control": JWKS_CACHE_CONTROL } },
      );
    }

    if (request.method === "GET" && path === "/.well-known/jwks.json") {
      return Response.json(
        { keys: PUBLIC_JWKS },
        { headers: { "Cache-Control": JWKS_CACHE_CONTROL } },
      );
    }

    return new Response("Not found", { status: 404 });
  },
};

// Exported for tests / operational sanity checks: the issuer should never
// serve a JWKS that's missing the key the gateway is actually signing with.
export function activeKeyIsPublished(): boolean {
  return PUBLIC_JWKS.some((k) => k.kid === ACTIVE_KID);
}
