// Standalone OIDC issuer for Cloudflare-worker → Azure federation.
//
// Publishes the discovery document + JWKS that Azure Entra fetches to validate
// the self-signed client assertions sessions-telemetry-gateway mints (see
// ./oidc-sign.ts and ./telemetry-gateway.ts). This is the whole point of the
// "zero Azure secret" design: no connection string or instrumentation key ever
// leaves this repo — Azure trusts this issuer's public key instead.
//
// This worker holds ONLY the public key. Signing happens in the telemetry
// gateway, which reads the matching private key from the OIDC_SIGNING_KEY
// Secrets Store entry. The `kid` below must match the `kid` the gateway stamps
// in its JWT header (OIDC_SIGNING_KID in hub/wrangler.telemetry-gateway.jsonc).
//
// Ported from youtube-mirror's worker/oidc-issuer.ts (GCP federation removed —
// this deployment only federates to Azure).

interface Env {
  ISSUER_URL: string;
}

// PLACEHOLDER — generated by `node scripts/generate-gateway-key.mjs` for local
// dev/typecheck only; NOT paired with any private key ever bound as
// OIDC_SIGNING_KEY. Swap this for the real public JWK at M4 deploy time (see
// infra/cf/telemetry.md "Rotate the signing key" / infra/azure/provision.sh),
// matching kid to OIDC_SIGNING_KID on the telemetry gateway.
const PUBLIC_JWK = {
  kty: "RSA",
  kid: "5c98ea52",
  n: "6G02tlLeCFnQbfBr_WjGYcd1q4MwXtrtu6Io2np4sszP2UOP3c9w46flw80EqWhKYO1YoaOPJGPtWuiYSOyLTXOfJ4q0wSF3zK2DR4aLyoJb_A1_khIdM2CCVs_Ec5eJOAAaSXRLr8SkV3D8ro_ejdsGrNKhooc3KJfy8K_joY2n9efTsN3LwSsibP_E3kyNWDzUyLykKdx6xOOW5M0T2Kj-IpzRc6sl4GcapvkEIBENOAcr5WbwqQ3VcG6zyy0sbaYiUCkhMbgOoQPnGhNpiF0mZAjehkkO00D7VIy6NNFFDKWaXO2cohH5kCUrgW7W4zbH8B6Y7bZr_b3Fkr5eeQ",
  e: "AQAB",
  alg: "RS256",
  use: "sig",
};

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const path = new URL(request.url).pathname;

    if (request.method === "GET" && path === "/.well-known/openid-configuration") {
      return Response.json(
        {
          issuer: env.ISSUER_URL,
          jwks_uri: `${env.ISSUER_URL}/.well-known/jwks.json`,
          response_types_supported: ["id_token"],
          subject_types_supported: ["public"],
          id_token_signing_alg_values_supported: ["RS256"],
        },
        { headers: { "Cache-Control": "public, max-age=3600" } },
      );
    }

    if (request.method === "GET" && path === "/.well-known/jwks.json") {
      return Response.json(
        { keys: [PUBLIC_JWK] },
        { headers: { "Cache-Control": "public, max-age=3600" } },
      );
    }

    return new Response("Not found", { status: 404 });
  },
};
